'use strict';

var config = {
  formId: 'tkf-skoleskyss',
  formName: 'Skoleskyss',
  initialState: {
    page: 1,
    formId:'',
    formVersion:'',
    personnummer: '',
    navn: '',
    folkeregistrert_adresse_bosted: '',
    folkeregistrert_adresse_adresse:'',
    folkeregistrert_adresse_gnr: '',
    folkeregistrert_adresse_bnr: '',
    folkeregistrert_adresse_kommunenr:'',
    alternativ_adresse: '',
    alternativ_adresse_bosted: '',
    alternativ_adresse_adresse:'',
    alternativ_adresse_gnr: '',
    alternativ_adresse_bnr: '',
    alternativ_adresse_kommunenr:'',
    telefon: '',
    epost: '',
    skole: '',
    klassetrinn: '',
    sokegrunnlag: '',
    busskortstatus: '',
    busskortnummer: '',
    eksternSkoleNavn: '',
    eksternSkoleAdresse: '',
    beregnetStatus:'',
    utregnetAvstandFolkeregistrert: '',
    utregnetAvstandAdresseFolkeregistrert: '',
    utregnetAvstandSkoleFolkeregistrert: '',
    utregnetAvstandKartFolkeregistrert: '',
    holdeplassHjemFolkeregistrert: '',
    overgangFolkeregistrert: '',
    utregnetAvstandAlternativt: '',
    utregnetAvstandAdresseAlternativt: '',
    utregnetAvstandSkoleAlternativt: '',
    utregnetAvstandKartAlternativt: '',
    holdeplassHjemAlternativt: '',
    overgangAlternativt: '',
    holdeplassSkole:'',
    utmFolkeregistrert:'',
    utmAlternativt:'',
    utmSkole:'',
    fullReiseFolkeregistrert:'',
    fullReiseAlternativt:''
  },
  kommuneListe : [
    {value:'', text:'Velg kommune', id:'007'},
    {value:'0814', text:'Bamble', id:'0814'},
    {value:'0821', text:'Bø', id:'0821'},
    {value:'0817', text:'Drangedal', id:'0817'},
    {value:'0831', text:'Fyresdal', id:'0831'},
    {value:'0827', text:'Hjartdal', id:'0827'},
    {value:'0815', text:'Kragerø', id:'0815'},
    {value:'0829', text:'Kviteseid', id:'0829'},
    {value:'0830', text:'Nissedal', id:'0830'},
    {value:'0819', text:'Nome', id:'0819'},
    {value:'0807', text:'Notodden', id:'0807'},
    {value:'0805', text:'Porsgrunn', id:'0805'},
    {value:'0822', text:'Sauherad', id:'0822'},
    {value:'0828', text:'Seljord', id:'0828'},
    {value:'0811', text:'Siljan', id:'0811'},
    {value:'0806', text:'Skien', id:'0806'},
    {value:'0826', text:'Tinn', id:'0826'},
    {value:'0833', text:'Tokke', id:'0833'},
    {value:'0834', text:'Vinje', id:'0834'}
  ],
  skoleListe: [
    {value:'', text:'Jeg skal gå på', id:'007'},
    {value:'Bamble videregående skole, Tønderveien 6, 3960 Stathelle', text:'Bamble videregående skole, avdeling Grasmyr', id:'39601'},
    {value:'Bamble videregående skole, Tostrupsvei 7, 3960 Stathelle', text:'Bamble videregående skole, avdeling Croftholmen', id:'39602'},
    {value:'Bø videregåande skule, Gymnasbakken 23, 3802 Bø', text:'Bø videregåande skule', id:'3802'},
    {value:'Hjalmar Johansen videregående skole, Moflatvegen 38, 3733 Skien',
      text:'Hjalmar Johansen videregående skole, avdeling Fritidsparken', id:'3733'},
    {value:'Hjalmar Johansen videregående skole, Olai Skulleruds veg 20, 3730 Skien',
      text:'Hjalmar Johansen videregående skole, avdeling Klosterskogen', id:'3730'},
    {value:'Kragerø videregående skole, Frydensborgveien 9-11, 3770 Kragerø',
      text:'Kragerø videregående skole', id:'3770'},
    {value:'Jakob Naadlandsveg 2, 3850 Kviteseid',
      text:'Kvitsund gymnas', id:'3850'},
    {value:'Nome videregående skole, Olav Strannas vei 25, 3825 Lunde',
      text:'Nome videregående skole, avdeling Lunde', id:'3825'},
    {value:'Nome videregående skole, Søveveien 8, 3830 Ulefoss',
      text:'Nome videregående skole, avdeling Søve', id:'3830'},
    {value:'Notodden videregående skole, Heddalsveien 4, 3674 Notodden',
      text:'Notodden videregående skole', id:'3674'},
    {value:'Porsgrunn videregående skole, Kjølnes Ring 58, 3918 Porsgrunn',
      text:'Porsgrunn videregående skole, avdeling Nord', id:'39181'},
    {value:'Porsgrunn videregående skole, Kjølnes Ring 20, 3918 Porsgrunn',
      text:'Porsgrunn videregående skole, avdeling Sør', id:'39182'},
    {value:'Rjukan videregående skole, Såheimveien 22, 3660 Rjukan',
      text:'Rjukan videregående skole', id:'3660'},
    {value:'Skien videregående skole, Rektor Ørns gate 2, 3717 Skien',
      text:'Skien videregående skole, avdeling Brekkeby', id:'3717'},
    {value:'Skien videregående skole, Einar Østvedts gate 12, 3724 Skien',
      text:'Skien videregående skole, avdeling Prestegjordet', id:'3724'},
    {value:'Skogmo videregående skole, Kjørbekkdalen 11, 3735 Skien',
      text:'Skogmo videregående skole', id:'3735'},
    {value:'Toppidrettsgymnaset i Telemark, Fritjof Nansens gate 19C, 3722 Skien',
      text:'Toppidrettsgymnaset i Telemark', id:'3722'},
    {value:'Vest-Telemark vidaregåande skule, Storvegen 195, 3880 Dalen',
      text:'Vest-Telemark vidaregåande skule, avdeling Dalen', id:'3880'},
    {value:'Vest-Telemark vidaregåande skule, Brøløsvegen 2, 3840 Seljord',
      text:'Vest-Telemark vidaregåande skule, avdeling Seljord', id:'3840'},
    {value:'Skole utenfor Telemark',
      text:'Skole utenfor Telemark', id:'0666'}
  ],
  SERVER_PORT: 3000,
  API_POST_HOST: 'api.t-fk.no',
  API_POST_PATH: '/forms',
  TRAVEL_API: 'https://api.t-fk.no/stages/travel'
};

module.exports = config;